name: Allure Report

env:
    SOLUTION_FILE: Issue440Reproduction.sln
    BUILD_CONFIGURATION: Debug

on:
  push:
    branches-ignore:
      - '!main'

jobs:
    autotests:
        name: Build and run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
  
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: |
                    7.0.x

            - name: Restore NuGet packages
              run: dotnet restore --packages .packages ${{ env.SOLUTION_FILE }}

            - name: Build solution
              run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}

            - name: Test solution
              run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}
              continue-on-error: true